package CIS2206.Unit_17;

import java.util.HashMap;
import java.util.Map;

public class User {
    public static void main(String[] args) {
        InventorySystem s1 = new InventorySystem();
        Order order1 = new Order("1","beans",3,4,"SHIPPED");
        s1.storeOrder("1", order1);
        Order order2 = new Order("2","toast",8,9,"PENDING");
        s1.storeOrder("2", order2);

        s1.listOrders();
        s1.trackOrder("1");

        s1.printOrdersByStatus("SHIPPED");
        s1.calculateRevenue();
        s1.cancelOrder("2", order2);

        Order order1update = new Order("1","beans heinz",3,4,"SHIPPED");
        s1.updateOrder("1",order1update);
        s1.listOrders();

        InventorySystem s2 = new InventorySystem();
        Order order3 = new Order("3","sausages",7,44,"SHIPPED");
        s2.storeOrder("3", order3);
        Order order4 = new Order("4","eggs",4,23,"PENDING");
        s2.storeOrder("4", order4);
        s2.listOrders();
        s2.calculateRevenue();

        // Class User:
        // Contains a main function driving events
        // Creates two inventory systems and subsequently places, updates, cancels, tracks and prints stored orders
        // Calculates the total revenue generated by each inventory system
    }
}
